export default [{
        url: "/dashboard",
        name: "Dashboard",
        slug: "home",
        icon: "HomeIcon",
        isMain : false,
    },
    {
        url: "/customers",
        name: "Customers",
        slug: "customers",
        icon: "UsersIcon",
    },
    {
        url: "/",
        name: "Companies",
        slug: "companies",
        icon: "UsersIcon",
        isMain : false,
        submenu: [{
                url: "/add-company",
                name: "Add Company",
                slug: "add-company",
                icon: "UserIcon",
                target : '_blank',
            },
            {
                url: "/companies",
                name: "List Of Companies",
                slug: "companies",
                icon: "UsersIcon",
            },
        ]
    },
    {
        url: "/currencies",
        name: "Currencies",
        slug: "currencies",
        icon: "DollarSignIcon",
        isMain : false,
    },
    {
        url: "/exchange-rates",
        name: "Exchange Rates",
        slug: "exchange-rates",
        icon: "ActivityIcon",
        isMain : false,
    },
    {
        url: "/",
        name: "Reports",
        slug: "Reports",
        icon: "BookOpenIcon",
        isMain : false,
    },
    {
        url: "/faqs",
        name: "Faqs",
        slug: "faqs",
        icon: "HelpCircleIcon",
        isMain : false,
    },
]
